import request from './request'
export const clusterApi={summary:()=>request.get('/cluster/summary'),pods:()=>request.get('/cluster/pods'),deployments:()=>request.get('/cluster/deployments'),events:(limit=100)=>request.get('/cluster/events',{params:{limit}}),logs:(pod,params={})=>request.get(`/cluster/pods/${encodeURIComponent(pod)}/logs`,{params})}
export const maintenanceDocumentApi={list:(params={})=>request.get('/maintenance-documents',{params}),get:name=>request.get(`/maintenance-documents/${encodeURIComponent(name)}`),upload:file=>{const data=new FormData();data.append('file',file);return request.post('/maintenance-documents',data)},remove:name=>request.delete(`/maintenance-documents/${encodeURIComponent(name)}`)}
export const knowledgeApi=maintenanceDocumentApi
export const backgroundApi={list:()=>request.get('/background/tasks'),get:id=>request.get(`/background/tasks/${id}`),approve:id=>request.post(`/background/tasks/${id}/approve`,{}, {headers:{'X-Operator':'frontend-user'}}),reject:id=>request.post(`/background/tasks/${id}/reject`,{}, {headers:{'X-Operator':'frontend-user'}})}
export const incidentApi={list:()=>request.get('/incidents'),get:id=>request.get(`/incidents/${id}`),context:id=>request.get(`/incidents/${id}/context`),messages:id=>request.get(`/incidents/${id}/messages`),actions:id=>request.get(`/incidents/${id}/actions`),propose:(id,data)=>request.post(`/incidents/${id}/actions`,data),confirm:(id,action)=>request.post(`/incidents/${id}/actions/${action}/confirm`,{}, {headers:{'X-Operator':'frontend-user'}}),reject:(id,action)=>request.post(`/incidents/${id}/actions/${action}/reject`,{}, {headers:{'X-Operator':'frontend-user'}}),create:data=>request.post('/incidents',data),resolve:id=>request.post(`/incidents/${id}/resolve`)}
export const workOrderApi={list:()=>request.get('/work-orders'),get:id=>request.get(`/work-orders/${id}`),messages:id=>request.get(`/work-orders/${id}/messages`),create:data=>request.post('/work-orders',data),complete:id=>request.post(`/work-orders/${id}/complete`),cancel:id=>request.post(`/work-orders/${id}/cancel`)}
export async function streamConversation(path,message,onToken){const response=await fetch(`/api${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});if(!response.ok)throw new Error('Agent 请求失败');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){const line=chunk.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;const data=line.slice(5).trim();if(data.includes('[DONE]'))return;onToken(data.replace(/^data:\s*/,''))}}}
export { request }
