<template>
  <div class="page">
    <div class="section-title"><div><div class="eyebrow">INCIDENT INVESTIGATION</div><h2>故障排查</h2><span class="muted">{{ incident?.alert_name }} · {{ incident?.status }}</span></div><n-button @click="resolve">标记已解决</n-button></div>
    <div class="incident-workspace">
      <div>
        <section class="panel"><div class="section-title"><h3>故障上下文</h3><n-tag :type="incident?.status === 'resolved' ? 'success' : 'warning'">{{ incident?.status || '加载中' }}</n-tag></div><n-descriptions bordered :column="1" size="small"><n-descriptions-item label="告警">{{ incident?.alert_name || '—' }}</n-descriptions-item><n-descriptions-item label="Fingerprint">{{ incident?.alert_fingerprint || '—' }}</n-descriptions-item><n-descriptions-item label="上下文"><pre class="context-preview">{{ pretty(incident?.context) }}</pre></n-descriptions-item></n-descriptions></section>
        <section class="panel" v-if="actions.length"><div class="section-title"><div><h3>待确认修复动作</h3><span class="muted">Agent 只提出方案，执行前必须确认</span></div></div><n-list><n-list-item v-for="action in actions" :key="action.id"><div><strong>{{ action.action_type }}</strong><div class="muted">目标：{{ action.namespace }}/{{ action.target }} · {{ action.reason }}</div><div class="muted">风险：{{ action.risk || '请确认影响范围' }}　回滚：{{ action.rollback || '按维护文档执行' }}</div></div><template #suffix><n-space v-if="action.status === 'pending_confirmation'"><n-button type="primary" size="small" @click="confirmAction(action.id)">确认执行</n-button><n-button size="small" @click="rejectAction(action.id)">拒绝</n-button></n-space><n-tag v-else>{{ action.status }}</n-tag></template></n-list-item></n-list></section>
        <section class="panel chat-main incident-chat"><div class="section-title"><div><h3>Incident Agent 对话</h3><span class="muted">专家和工具调用会直接显示在对话时间线上</span></div><n-tag v-if="streaming" type="info">分析中</n-tag></div><div class="messages"><template v-for="(message, index) in messages" :key="message.id || `${message.created_at || index}-${index}`"><div v-if="message.kind === 'activity'" :class="['message', 'execution-message', `execution-${message.status}`]"><div class="execution-summary"><span class="execution-glyph">{{ message.status === 'failed' ? '!' : message.status === 'completed' ? '✓' : '·' }}</span><strong>{{ message.title }}</strong><n-tag size="small" :type="runtimeStatusType(message.status)">{{ executionStatusLabel(message.status) }}</n-tag></div><p v-if="message.detail" class="execution-detail">{{ message.detail }}</p><details v-if="message.payload"><summary>查看执行详情</summary><pre>{{ pretty(message.payload) }}</pre></details></div><div v-else :class="['message', message.role]">{{ message.content }}</div></template><div v-if="streaming" class="typing-indicator"><span></span><span></span><span></span><em>Agent 正在分析</em></div></div><div class="chat-input"><n-input v-model:value="input" placeholder="描述现象或询问 Agent 下一步排查..." @keydown.enter.exact.prevent="send"/><n-button type="primary" :loading="streaming" @click="send">发送</n-button></div></section>
      </div>
      <div><section class="panel execution-panel"><div class="section-title"><div><h3>Agent 执行过程</h3><span class="muted">不展示思维链，只展示专家、工具和结构化状态</span></div><n-button quaternary size="small" @click="loadRuntime">刷新</n-button></div><n-tabs type="line" animated><n-tab-pane name="live" tab="实时事件"><n-empty v-if="!activity.length" description="发送问题后显示实时执行过程"/><div v-else class="activity-list"><div v-for="(item, index) in activity" :key="`${item.at}-${index}`" class="activity-item"><n-tag size="small" :type="activityType(item.type)">{{ activityLabel(item.type) }}
      </n-tag><div><strong>{{ item.title }}</strong><p>{{ item.detail }}</p></div></div></div></n-tab-pane><n-tab-pane name="workers" tab="专家结果"><n-empty v-if="!workers.length" description="暂无专家执行记录"/><div v-else class="runtime-list"><div v-for="worker in workers" :key="worker.id" class="runtime-card"><div class="runtime-card-head"><strong>{{ worker.agent_name }}</strong><n-tag size="small" :type="runtimeStatusType(worker.status)">{{ worker.status }}
      </n-tag></div><p>{{ worker.result || worker.error || '正在执行' }}</p></div></div></n-tab-pane><n-tab-pane name="tools" tab="工具调用"><n-empty v-if="!toolCalls.length" description="暂无工具调用记录"/><div v-else class="runtime-list"><div v-for="call in toolCalls" :key="call.id" class="runtime-card"><div class="runtime-card-head"><strong>{{ call.tool_name }}</strong><n-tag size="small" :type="runtimeStatusType(call.status)">{{ call.status }}
      </n-tag></div><p v-if="call.result">{{ call.result }}</p><p v-else-if="call.error" class="error-text">{{ call.error }}</p><small v-if="call.arguments">参数：{{ call.arguments }}</small></div></div></n-tab-pane></n-tabs></section></div>
    </div>
  </div>
</template>
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import { useNotification } from 'naive-ui'
import { incidentApi, request, streamConversation } from '@/api'
const route = useRoute(); const notification = useNotification(); const incident = ref(null); const actions = ref([]); const messages = ref([]); const workers = ref([]); const toolCalls = ref([]); const activity = ref([]); const input = ref(''); const streaming = ref(false); const activeAssistantIndex = ref(-1)
function pretty(value){if(!value)return '{}';try{return JSON.stringify(typeof value==='string'?JSON.parse(value):value,null,2)}catch{return String(value)}}
function activityLabel(type){return({run_started:'Agent 启动',worker_started:'专家启动',worker_completed:'专家完成',worker_failed:'专家失败',tool_started:'工具调用',tool_completed:'工具完成',tool_failed:'工具失败',run_completed:'分析完成',run_failed:'Agent 失败'}[type]||type)}
function activityType(type){return type?.includes('failed')?'error':type?.includes('completed')?'success':'info'}
function runtimeStatusType(status){return status==='completed'||status==='success'?'success':status==='failed'?'error':'info'}
function executionStatusLabel(status){return({running:'执行中',completed:'已完成',failed:'失败'}[status]||'处理中')}
function decodeEventData(data){if(!data)return null;if(typeof data==='string'){try{return JSON.parse(data)}catch{return {result:data}}}return data}
function shortText(value,max=260){const text=String(value||'');return text.length>max?`${text.slice(0,max)}…`:text}
function eventDetail(data){const value=decodeEventData(data);if(!value)return '';if(value.error)return `错误：${shortText(value.error)}`;if(value.result)return shortText(value.result);if(value.tool_name)return `调用工具：${value.tool_name}`;if(value.agent_name)return `专家：${value.agent_name}`;if(value.agent)return `Agent：${value.agent}`;return ''}
function eventTitle(type,data){const value=decodeEventData(data)||{};const name=value.tool_name||value.agent_name||value.agent;return({run_started:'Incident Agent 已启动',worker_started:`${name||'专家'}正在分析`,worker_completed:`${name||'专家'}分析完成`,worker_failed:`${name||'专家'}分析失败`,tool_started:`正在调用 ${name||'观测工具'}`,tool_completed:`${name||'观测工具'}返回结果`,tool_failed:`${name||'观测工具'}调用失败`,run_completed:'Incident Agent 分析完成',run_failed:'Incident Agent 执行失败'}[type]||type)}
function eventStatus(type,data){const value=decodeEventData(data);if(value?.status==='failed'||type.includes('failed'))return 'failed';if(value?.status==='completed'||type.includes('completed'))return 'completed';return 'running'}
function eventGroup(type){return type?.startsWith('worker_')?'worker':type?.startsWith('tool_')?'tool':''}
function normalizeActivity(type,data,at=new Date().toISOString()){const value=decodeEventData(data);const group=eventGroup(type);return{kind:'activity',id:group&&value?.id?value.id:`${type}-${at}-${Math.random()}`,group,type,title:eventTitle(type,value),detail:eventDetail(value),payload:value?.result||value?.error||value?.arguments?{result:value?.result,error:value?.error,arguments:value?.arguments}:null,status:eventStatus(type,value),created_at:at}}
function activityForItem(item){return{id:item.id,type:item.type,title:item.title,detail:item.detail,at:item.created_at,group:item.group,status:item.status}}
function pushRuntimeEvent(type,data){const item=normalizeActivity(type,data);const existingIndex=item.group?messages.value.findIndex(entry=>entry.kind==='activity'&&entry.group===item.group&&entry.id===item.id):-1;if(existingIndex>=0){messages.value.splice(existingIndex,1,{...messages.value[existingIndex],...item})}else{const index=activeAssistantIndex.value;if(index>=0&&messages.value[index]?.kind==='message'&&!messages.value[index].content){messages.value.splice(index,0,item);activeAssistantIndex.value++}else messages.value.push(item)}const liveIndex=item.group?activity.value.findIndex(entry=>entry.group===item.group&&entry.id===item.id):-1;if(liveIndex>=0)activity.value.splice(liveIndex,1,activityForItem(item));else activity.value.push(activityForItem(item))}
function mergeRuntimeItems(rows){const output=[];for(const row of rows||[]){const item=normalizeActivity(row.event_name,row.output||row.error,row.created_at);const index=item.group?output.findIndex(existing=>existing.group===item.group&&existing.id===item.id):-1;if(index>=0)output[index]={...output[index],...item};else output.push(item)}return output}
function mergeConversation(messageRows,timelineRows){const items=[...(messageRows||[]).map(item=>({...item,kind:'message',created_at:item.created_at||''})),...mergeRuntimeItems(timelineRows)];return items.sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)))}
async function load(){try{incident.value=await incidentApi.get(route.params.id);const[m,a]=await Promise.all([request.get(`/incidents/${route.params.id}/messages`),incidentApi.actions(route.params.id)]);messages.value=(m.messages||[]).map(item=>({kind:'message',id:item.id,role:item.role,content:item.content,created_at:item.created_at}));actions.value=a.actions||[];await loadRuntime()}catch(error){notification.error({title:'故障详情加载失败',content:error.message})}}
async function loadRuntime(){try{const[w,t,history]=await Promise.all([incidentApi.workers(route.params.id),incidentApi.toolCalls(route.params.id),incidentApi.timeline(route.params.id)]);workers.value=w.workers||[];toolCalls.value=t['tool-calls']||t.tool_calls||[];if(!streaming.value){const conversationMessages=messages.value.filter(item=>item.kind!=='activity');const runtimeItems=mergeRuntimeItems(history.timeline||[]);messages.value=mergeConversation(conversationMessages,history.timeline||[]);activity.value=runtimeItems.map(activityForItem)}}catch(error){notification.error({title:'执行记录加载失败',content:error.message})}}
async function send(){const question=input.value.trim();if(!question||streaming.value)return;input.value='';messages.value.push({kind:'message',role:'user',content:question,created_at:new Date().toISOString()},{kind:'message',role:'assistant',content:'',created_at:new Date().toISOString()});activeAssistantIndex.value=messages.value.length-1;activity.value=[];streaming.value=true;try{await streamConversation(`/incidents/${route.params.id}/chatStream`,question,token=>{const assistant=messages.value[activeAssistantIndex.value];if(assistant)assistant.content+=token},(event,data)=>pushRuntimeEvent(event,data));await loadRuntime()}catch(error){const assistant=messages.value[activeAssistantIndex.value];if(assistant)assistant.content=(assistant.content?`${assistant.content}\n\n`:'')+`请求失败：${error.message}`;pushRuntimeEvent('run_failed',{error:error.message});notification.error({title:'Incident Agent 请求失败',content:error.message,duration:8000})}finally{activeAssistantIndex.value=-1;streaming.value=false}}
async function confirmAction(id){await incidentApi.confirm(route.params.id,id);await load()}
async function rejectAction(id){await incidentApi.reject(route.params.id,id);await load()}
async function resolve(){await request.post(`/incidents/${route.params.id}/resolve`);await load()}
let timer;onMounted(()=>{load();timer=setInterval(loadRuntime,5000)});onUnmounted(()=>clearInterval(timer))
</script>
