apiVersion: v1
kind: Service
metadata:
  name: autoops-test-server
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: autoops-test-server
    app.kubernetes.io/part-of: autoops
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: autoops-test-server
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      nodePort: {{ .Values.service.nodePort }}
