apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autoops-test-server
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: autoops-test-server
  namespaceSelector:
    matchNames: [{{ .Values.namespace }}]
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.interval }}
